export default function PrivacyPolicyEN() {
  return (
    <div className="max-w-4xl mx-auto mb-16 space-y-8 text-secondary">
      {/* Introduction */}
      <section className="space-y-4">
        <p className="leading-relaxed">
          This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
        </p>
        <p className="leading-relaxed">
          We use Your Personal Data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.
        </p>
      </section>

      {/* Interpretation and Definitions */}
      <section className="space-y-4">
        <h2 className="text-2xl font-semibold text-primary">Interpretation and Definitions</h2>
        
        <div>
          <h3 className="text-lg font-semibold text-primary mb-2">Interpretation</h3>
          <p className="leading-relaxed">
            The words whose initial letters are capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
          </p>
        </div>

        <div>
          <h3 className="text-lg font-semibold text-primary mb-4">Definitions</h3>
          <p className="leading-relaxed mb-4">For the purposes of this Privacy Policy:</p>
          <ul className="space-y-3 ml-4 list-disc">
            <li className="leading-relaxed"><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
            <li className="leading-relaxed"><strong>Affiliate</strong> means an entity that controls, is controlled by, or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
            <li className="leading-relaxed"><strong>Application</strong> refers to Carendoo, the software program provided by the Company.</li>
            <li className="leading-relaxed"><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Privacy Policy) refers to the individual creator and independent developer of the Carendoo Application.</li>
            <li className="leading-relaxed"><strong>Country</strong> refers to: Poland</li>
            <li className="leading-relaxed"><strong>Device</strong> means any device that can access the Service such as a computer, a cell phone or a digital tablet.</li>
            <li className="leading-relaxed"><strong>Personal Data</strong> (or "Personal Information") is any information that relates to an identified or identifiable individual.</li>
            <li className="leading-relaxed"><strong>Service</strong> refers to the Application.</li>
            <li className="leading-relaxed"><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</li>
            <li className="leading-relaxed"><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
            <li className="leading-relaxed"><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
          </ul>
        </div>
      </section>

      {/* Collecting and Using Your Personal Data */}
      <section className="space-y-4">
        <h2 className="text-2xl font-semibold text-primary">Collecting and Using Your Personal Data</h2>
        
        <div>
          <h3 className="text-lg font-semibold text-primary mb-4">Types of Data Collected</h3>
          
          <div className="mb-6">
            <h4 className="font-semibold text-primary mb-3">Personal Data</h4>
            <p className="leading-relaxed mb-3">
              While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:
            </p>
            <ul className="list-disc ml-6 space-y-2">
              <li className="leading-relaxed">Email address</li>
            </ul>
          </div>

          <div className="mb-6">
            <h4 className="font-semibold text-primary mb-3">Usage Data</h4>
            <p className="leading-relaxed mb-3">
              Usage Data is collected automatically when using the Service.
            </p>
            <p className="leading-relaxed mb-3">
              Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
            </p>
            <p className="leading-relaxed">
              When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device's unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.
            </p>
          </div>

          <div>
            <h4 className="font-semibold text-primary mb-3">Information Collected while Using the Application</h4>
            <p className="leading-relaxed mb-3">
              While using Our Application, in order to provide features of Our Application, We may collect, with Your prior permission:
            </p>
            <ul className="list-disc ml-6 space-y-2 mb-3">
              <li className="leading-relaxed">Information regarding your location</li>
              <li className="leading-relaxed">Pictures and other information from your Device's camera and photo library</li>
            </ul>
            <p className="leading-relaxed">
              We use this information to provide features of Our Service, to improve and customize Our Service. The information may be securely uploaded to the Company's backend infrastructure managed by our Service Providers, or it may be simply stored on Your device. You can enable or disable access to this information at any time through Your Device settings.
            </p>
          </div>
        </div>
      </section>

      {/* Use of Your Personal Data */}
      <section className="space-y-4">
        <h2 className="text-2xl font-semibold text-primary">Use of Your Personal Data</h2>
        <p className="leading-relaxed mb-4">The Company may use Personal Data for the following purposes:</p>
        <ul className="space-y-3 ml-4">
          <li className="leading-relaxed"><strong>To provide and maintain our Service</strong>, including to monitor the usage of our Service.</li>
          <li className="leading-relaxed"><strong>To manage Your Account</strong>: to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.</li>
          <li className="leading-relaxed"><strong>For the performance of a contract</strong>: The development, compliance and undertaking of the purchase contract for the products, items or services You have purchased (such as premium subscriptions or additional features) or of any other contract with Us through the Service.</li>
          <li className="leading-relaxed"><strong>To contact You</strong>: To contact You by email regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.</li>
          <li className="leading-relaxed"><strong>To manage Your requests</strong>: To attend and manage Your requests to Us.</li>
          <li className="leading-relaxed"><strong>For crash reporting and performance monitoring</strong>: To automatically collect diagnostic data, crash logs, and performance metrics to help us fix bugs and improve application stability.</li>
          <li className="leading-relaxed"><strong>For other purposes</strong>: We may use Your information for data analysis, identifying usage trends, and to evaluate and improve our Service, products, marketing and your experience.</li>
        </ul>
      </section>

      {/* Sharing and Storage */}
      <section className="space-y-4">
        <h2 className="text-2xl font-semibold text-primary">Sharing and Storage of Your Personal Data</h2>
        <p className="leading-relaxed mb-4">
          We share and process your Personal Data only with trusted third-party services necessary to run the Application. We may disclose Your information in the following situations:
        </p>
        <ul className="space-y-4 ml-4">
          <li className="leading-relaxed">
            <strong>With Cloud Infrastructure and Database Providers (Supabase)</strong>: We use Supabase (Supabase Inc.) as our main backend and database provider. Your Account Information and Application data are securely stored on their servers.
          </li>
          <li className="leading-relaxed">
            <strong>With Diagnostics and Crash Analytics Providers (Sentry)</strong>: We use Sentry (Functional Software, Inc.) to monitor application errors. Sentry may collect limited device diagnostics and crash logs when an error occurs to help us maintain software stability.
          </li>
          <li className="leading-relaxed">
            <strong>For Payment Processing (In-App Purchases)</strong>: All financial transactions, premium subscriptions, or digital purchases are handled directly and securely by the Apple App Store or Google Play Store. We do not collect, store, or have access to your payment card details, bank account info, or billing data.
          </li>
          <li className="leading-relaxed">
            <strong>With Your consent</strong>: We may disclose Your Personal Data for any other purpose with Your consent.
          </li>
          <li className="leading-relaxed">
            <strong>Under Law enforcement</strong>: Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).
          </li>
        </ul>
      </section>

      {/* Retention */}
      <section className="space-y-4">
        <h2 className="text-2xl font-semibold text-primary">Retention of Your Personal Data</h2>
        <p className="leading-relaxed mb-4">
          The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy, or as permitted under applicable data protection laws.
        </p>
        <p className="leading-relaxed mb-4">We apply different retention periods to different categories of Personal Data:</p>
        <ul className="space-y-3 ml-4">
          <li className="leading-relaxed"><strong>Account Information</strong>: User Accounts are retained for the duration of your active account relationship plus up to 24 months after account closure to handle any post-termination issues or resolve disputes.</li>
          <li className="leading-relaxed"><strong>Customer Support Data</strong>: Support tickets and email correspondence are kept for up to 24 months from the date of ticket closure to resolve follow-up inquiries.</li>
          <li className="leading-relaxed"><strong>Usage Data & Analytics</strong>: Server logs, IP addresses, and diagnostic crash data via Sentry are stored for up to 24 months for security monitoring, troubleshooting, and feature adoption analysis.</li>
        </ul>
        <p className="leading-relaxed mt-4">
          When retention periods expire, We securely delete or anonymize Personal Data so it cannot be linked back to You. Residual encrypted copies may remain in automated system backups for a limited period until they are routinely overwritten.
        </p>
      </section>

      {/* Transfer of Data */}
      <section className="space-y-4">
        <h2 className="text-2xl font-semibold text-primary">Transfer of Your Personal Data</h2>
        <p className="leading-relaxed mb-4">
          Your information, including Personal Data, is processed at the Company's operating locations and in any other places where the parties involved in the processing (such as Supabase or Sentry) are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ from those from Your jurisdiction.
        </p>
        <p className="leading-relaxed">
          The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy.
        </p>
      </section>

      {/* Delete Your Data */}
      <section className="space-y-4">
        <h2 className="text-2xl font-semibold text-primary">Delete Your Personal Data</h2>
        <p className="leading-relaxed mb-4">
          You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You.
        </p>
        <p className="leading-relaxed mb-4">
          Our Service gives You the ability to delete certain information about You, as well as your entire account, directly from within the Application's account settings section. You may also contact Us via email to request access to, correct, or delete any Personal Data that You have provided to Us.
        </p>
        <p className="leading-relaxed">
          Please note, however, that We may need to retain certain information when we have a legal obligation or lawful basis to do so.
        </p>
      </section>

      {/* Security */}
      <section className="space-y-4">
        <h2 className="text-2xl font-semibold text-primary">Security of Your Personal Data</h2>
        <p className="leading-relaxed">
          The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data through modern cloud standards, We cannot guarantee its absolute security.
        </p>
      </section>

      {/* Children's Privacy */}
      <section className="space-y-4">
        <h2 className="text-2xl font-semibold text-primary">Children's Privacy</h2>
        <p className="leading-relaxed">
          Our Service does not address anyone under the age of 16. We do not knowingly collect personally identifiable information from anyone under the age of 16. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 16 without verification of parental consent, We take steps to remove that information from our storage systems.
        </p>
      </section>

      {/* Links to Other Websites */}
      <section className="space-y-4">
        <h2 className="text-2xl font-semibold text-primary">Links to Other Websites</h2>
        <p className="leading-relaxed mb-4">
          Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.
        </p>
        <p className="leading-relaxed">
          We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.
        </p>
      </section>

      {/* Changes to Policy */}
      <section className="space-y-4">
        <h2 className="text-2xl font-semibold text-primary">Changes to this Privacy Policy</h2>
        <p className="leading-relaxed mb-4">
          We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.
        </p>
        <p className="leading-relaxed">
          We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the "Last updated" date at the top of this Privacy Policy. You are advised to review this Privacy Policy periodically for any changes.
        </p>
      </section>

      {/* Contact Us */}
      <section className="space-y-4 border-t border-gray-200 pt-6">
        <h2 className="text-2xl font-semibold text-primary">Contact Us</h2>
        <p className="leading-relaxed mb-4">
          If you have any questions about this Privacy Policy, You can contact us:
        </p>
        <p className="leading-relaxed">
          <strong>By email:</strong> contact@carendoo.com
        </p>
      </section>
    </div>
  );
}
