name: Lint and Build Check

on:
  pull_request:
    branches:
      - master

jobs:
  lint-and-build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Remove package-lock.json and node_modules
        run: rm -rf package-lock.json node_modules

      - name: Clean npm cache
        run: npm cache clean --force

      - name: Install dependencies
        run: npm install --verbose

      - name: Run linter
        run: npm run lint

      - name: Build project
        run: npm run build
